name: Run Test Suites

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Check out your repository
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.101'
    - name: build project
      run: dotnet build src/HelloWorld.sln
    - name: test and collect coverage
      run: dotnet test src/HelloWorld.Tests/HelloWorld.Tests.csproj --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
    - name: upload coverage
      run: bash <(curl -s https://codecov.io/bash)
