name: Run Test Suites

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Check out your repository
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: build project
      run: dotnet build src/HelloWorld.sln
